### ISSUE TITLE
Links in HTML broken if there is a space in project path

### ISSUE THREAD

**Issue by iwane-pl** [spirali/nedoc#6]
My Python source folder has a space in it's name (`Python Scripts`). Building documentation results in broken links in HTML - the browser can't find a proper page.

Affected link example:
`<a class="symbol" href="Python Scripts.python_functions.base.log.html">log</a>`

Clicking on the link results in browser's attempt to open "Python" page - which does not exist.

**Comment by spirali** [comment]
I have tried the fix problem in the master. Can you try it, please?

**Comment by iwane-pl** [comment]
Works, thank you!
